name: test

on:
    push:
        branches:
        - "main"

jobs:
    test_ads:
        runs-on: ubuntu-20.04
        steps:
            - name: Show message
              run: echo "Hello world 2024-05-14"

            - name: Show secret
              run: echo ${{secrets.ENVIROMENT}}
